apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-11-25T22:40:50Z
  generation: 1
  labels:
    app: demoservice1
    chart: demoservice1-0.1.2
    heritage: Tiller
    release: release1
  name: release1-demoservice1
  namespace: default
  resourceVersion: "41412769"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/release1-demoservice1
  uid: b03a256a-d231-11e7-87db-42010af00032
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoservice1
      appversion: "17"
      release: release1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demoservice1
        appversion: "17"
        release: release1
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: demoservice1-config
        image: verchol/demo-service1:master
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: demoservice1
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /mongo
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2017-11-25T22:40:51Z
    lastUpdateTime: 2017-11-25T22:40:51Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
